phase: "07_statistical_analysis"
working_dir: "/home/dreece23/sims-pca-ws/07_statistical_analysis"
allow_write:
  - "07_statistical_analysis/**"
read_only_inputs:
  - "/home/dreece23/sims-pca-ws/out/*_renamed.tsv"
  - "/home/dreece23/sims-pca-ws/02_preprocessing/normalized/**"
  - "/home/dreece23/sims-pca-ws/03_pca_analysis/**"
  - "/home/dreece23/sims-pca-ws/05_chemical_interpretation/**"
  - "/home/dreece23/sims-pca-ws/_shared/**"
require_update: "/home/dreece23/sims-pca-ws/_shared/state/STATUS.json"