#!/bin/bash
# Review before running; moves files to new locations.
#
# QC Preprocessing Relocation Script  
# Moves preprocessing-related QC artifacts from qc/ to 02_preprocessing/qc/
# Leaves other QC files in place and creates index policy
#
# Usage: bash scripts/cleanup_move_qc_to_preprocessing.sh

set -euo pipefail

echo "=== QC Preprocessing Relocation Script ==="
echo "Date: $(date)"
echo

# Ensure target directory exists
echo "Ensuring 02_preprocessing/qc/ directory exists..."
mkdir -p 02_preprocessing/qc/

# Check if we're in a git repository
if [ -d ".git" ]; then
    MOVE_CMD="git mv"
    echo "Git repository detected - using 'git mv'"
else
    MOVE_CMD="mv"
    echo "Not a git repository - using 'mv'"
fi

echo

# Define preprocessing QC file patterns to move
PATTERNS=(
    "qc/normalization_comparison_*"
    "qc/tic_distribution_*" 
    "qc/*qc*.*"
    "qc/intensity_heatmap_*"
    "qc/correlation_matrix_*"
)

MOVED_COUNT=0

for pattern in "${PATTERNS[@]}"; do
    echo "Checking pattern: $pattern"
    
    # Use find to get matching files (handles spaces better than glob)
    while IFS= read -r -d '' file; do
        if [ -f "$file" ]; then
            TARGET="02_preprocessing/${file}"
            echo "  Moving: $file -> $TARGET"
            $MOVE_CMD "$file" "$TARGET"
            ((MOVED_COUNT++))
        fi
    done < <(find . -path "./$pattern" -type f -print0 2>/dev/null || true)
done

echo
echo "Total files moved: $MOVED_COUNT"

# Create/overwrite qc/README.md with index-only policy
echo "Creating qc/README.md with index-only policy..."
cat > qc/README.md << 'EOF'
# QC Directory Index Policy

**Status**: Index-only directory  
**Policy**: No QC artifacts stored here  

## Artifact Locations

All QC artifacts have been moved to their respective phase directories:

- **Preprocessing QC**: `02_preprocessing/qc/`
- **PCA Analysis QC**: `03_pca_analysis/qc/` (if applicable)
- **Statistical QC**: `07_statistical_analysis/qc/` (if applicable)

## Purpose

This directory serves only as an index and legacy reference point. All new QC artifacts should be generated directly in their appropriate phase directories according to the governance policy.

## Background

This reorganization ensures:
- QC artifacts are co-located with their analysis phase
- Phase isolation is maintained per governance rules
- Clear provenance and organization of QC outputs

---
*Generated by cleanup_move_qc_to_preprocessing.sh*
EOF

echo "✅ qc/README.md created with index-only policy"

echo
echo "=== QC Relocation Complete ==="
echo "Files moved to 02_preprocessing/qc/ for better phase organization"